// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// ════════════════════════════════════════════════════════════════════════════
//  FILE 1: MockGroth16Verifier
//  Deploy FIRST — always returns true (for hackathon demo)
//  For production: replace with the Groth16Verifier.sol generated by snarkjs
// ════════════════════════════════════════════════════════════════════════════

contract MockGroth16Verifier {
    function verifyProof(
        uint[2] calldata,
        uint[2][2] calldata,
        uint[2] calldata,
        uint[3] calldata
    ) external pure returns (bool) {
        return true;
    }
}
