/**
 * Off-chain client library for ZK Time-Decay Voting
 *
 * Handles:
 * - Generating voter credentials (nullifier, secret, commitment)
 * - Building Merkle proofs
 * - Generating ZK proofs via snarkjs
 * - Submitting votes to the contract
 *
 * Usage:
 *   const client = new VotingClient(provider, votingContractAddress);
 *   const credentials = client.generateCredentials();
 *   await client.register(credentials.commitment);
 *   // ... after registration closes ...
 *   await client.vote(credentials, voteChoice, merkleProof);
 */

const snarkjs = require("snarkjs");
const { ethers } = require("ethers");
const fs = require("fs");
const path = require("path");

// Paths to circuit artifacts (generated by setupCircuit.js)
const WASM_PATH = path.join(__dirname, "..", "build", "circuits", "vote_js", "vote.wasm");
const ZKEY_PATH = path.join(__dirname, "..", "build", "circuits", "vote_final.zkey");

class VotingClient {
  /**
   * @param {ethers.Provider} provider - Ethers.js provider
   * @param {string} votingAddress - Deployed ZKTimeDecayVoting contract address
   * @param {ethers.Signer} signer - Signer for sending transactions
   */
  constructor(provider, votingAddress, signer) {
    this.provider = provider;
    this.signer = signer;

    const abi = [
      "function registerVoter(uint256 commitment) external",
      "function castVote(uint[2] _pA, uint[2][2] _pB, uint[2] _pC, uint256 _root, uint256 _nullifierHash, uint256 _voteChoice) external",
      "function getMerkleRoot() external view returns (uint256)",
      "function getCurrentWeight() external view returns (uint256)",
      "function getVoteTally(uint256 choice) external view returns (uint256)",
      "function votingStart() external view returns (uint256)",
      "function votingEnd() external view returns (uint256)",
      "function numChoices() external view returns (uint256)",
      "event VoterRegistered(uint256 indexed commitment, uint256 leafIndex, uint256 newRoot)",
      "event VoteCast(uint256 indexed nullifierHash, uint256 choice, uint256 weight, uint256 timestamp)",
    ];

    this.contract = new ethers.Contract(votingAddress, abi, signer);
  }

  /**
   * Generate random voter credentials
   * @returns {{ nullifier: bigint, secret: bigint, commitment: bigint }}
   */
  generateCredentials() {
    // Generate cryptographically random field elements
    const nullifier = BigInt("0x" + ethers.hexlify(ethers.randomBytes(31)).slice(2));
    const secret = BigInt("0x" + ethers.hexlify(ethers.randomBytes(31)).slice(2));

    // NOTE: In production, compute commitment using the actual Poseidon hash.
    // This requires circomlibjs or @zk-kit/poseidon:
    //   const { buildPoseidon } = require("circomlibjs");
    //   const poseidon = await buildPoseidon();
    //   const commitment = poseidon.F.toString(poseidon([nullifier, secret]));
    console.log("⚠️  Remember to compute commitment with Poseidon(nullifier, secret)");

    return { nullifier, secret, commitment: null };
  }

  /**
   * Register a commitment on-chain
   * @param {bigint} commitment - Poseidon(nullifier, secret)
   */
  async register(commitment) {
    const tx = await this.contract.registerVoter(commitment);
    const receipt = await tx.wait();
    console.log(`✅ Registered commitment. TX: ${receipt.hash}`);

    // Extract leaf index from event
    const event = receipt.logs.find((log) => {
      try {
        return this.contract.interface.parseLog(log)?.name === "VoterRegistered";
      } catch {
        return false;
      }
    });

    if (event) {
      const parsed = this.contract.interface.parseLog(event);
      return {
        leafIndex: Number(parsed.args.leafIndex),
        newRoot: parsed.args.newRoot,
      };
    }
  }

  /**
   * Generate a ZK proof and cast a vote
   * @param {object} credentials - { nullifier, secret }
   * @param {number} voteChoice - Index of the voting option
   * @param {bigint} root - Merkle root to prove against
   * @param {bigint[]} pathElements - Merkle proof sibling hashes
   * @param {number[]} pathIndices - Merkle proof path direction (0=left, 1=right)
   */
  async vote(credentials, voteChoice, root, pathElements, pathIndices) {
    // 1. Compute nullifierHash off-chain (must match circuit)
    // In production: nullifierHash = Poseidon(nullifier)
    console.log("Generating ZK proof...");

    const input = {
      // Public inputs
      root: root.toString(),
      nullifierHash: "0", // Replace with actual Poseidon(nullifier)
      voteChoice: voteChoice.toString(),
      // Private inputs
      nullifier: credentials.nullifier.toString(),
      secret: credentials.secret.toString(),
      pathElements: pathElements.map((e) => e.toString()),
      pathIndices: pathIndices,
    };

    // 2. Generate the proof
    const { proof, publicSignals } = await snarkjs.groth16.fullProve(
      input,
      WASM_PATH,
      ZKEY_PATH
    );

    console.log("✅ ZK proof generated");
    console.log("   Public signals:", publicSignals);

    // 3. Format for Solidity
    const calldata = await snarkjs.groth16.exportSolidityCallData(proof, publicSignals);
    const args = JSON.parse("[" + calldata + "]");

    const [pA, pB, pC, pubSignals] = args;

    // 4. Send the transaction
    const tx = await this.contract.castVote(
      pA,
      pB,
      pC,
      pubSignals[0], // root
      pubSignals[1], // nullifierHash
      pubSignals[2]  // voteChoice
    );

    const receipt = await tx.wait();
    console.log(`✅ Vote cast! TX: ${receipt.hash}`);

    return receipt;
  }

  /**
   * Get current voting weight
   */
  async getCurrentWeight() {
    const weight = await this.contract.getCurrentWeight();
    // Convert from fixed-point to percentage
    const percentage = Number(weight) / 1e16;
    return { raw: weight, percentage: percentage.toFixed(2) + "%" };
  }

  /**
   * Get all tallies
   */
  async getTallies() {
    const numChoices = await this.contract.numChoices();
    const tallies = [];
    for (let i = 0; i < Number(numChoices); i++) {
      const tally = await this.contract.getVoteTally(i);
      tallies.push({
        choice: i,
        weightedVotes: tally,
        humanReadable: Number(tally) / 1e18,
      });
    }
    return tallies;
  }
}

module.exports = { VotingClient };
