/**
 * Deployment Script for ZK Time-Decay Voting
 *
 * Deploys:
 * 1. Poseidon T3 hasher contract
 * 2. Groth16Verifier contract (generated by snarkjs)
 * 3. ZKTimeDecayVoting main contract
 *
 * Usage:
 *   npx hardhat run scripts/deploy.js --network sepolia
 */

const hre = require("hardhat");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with account:", deployer.address);
  console.log("Balance:", hre.ethers.formatEther(await hre.ethers.provider.getBalance(deployer.address)), "ETH");

  // ── 1. Deploy Groth16Verifier ──
  console.log("\n📦 Deploying Groth16Verifier...");
  const Verifier = await hre.ethers.getContractFactory("Groth16Verifier");
  const verifier = await Verifier.deploy();
  await verifier.waitForDeployment();
  const verifierAddr = await verifier.getAddress();
  console.log("✅ Groth16Verifier deployed at:", verifierAddr);

  // ── 2. Deploy Poseidon T3 Hasher ──
  // NOTE: For the hackathon, you should deploy a Poseidon hasher contract.
  // You can generate it using:
  //   const { buildPoseidonT3 } = require("@zk-kit/poseidon");
  //   or use circomlibjs to generate the bytecode.
  //
  // For now, we'll use a placeholder — replace POSEIDON_ADDRESS with the actual address
  // after deploying via a helper script or manually.
  console.log("\n📦 Deploy Poseidon T3 hasher separately using @zk-kit/poseidon or circomlibjs");
  console.log("   See: https://github.com/privacy-scaling-explorations/zk-kit");

  // REPLACE THIS with your deployed Poseidon hasher address:
  const poseidonAddr = process.env.POSEIDON_ADDRESS || "0x0000000000000000000000000000000000000000";

  if (poseidonAddr === "0x0000000000000000000000000000000000000000") {
    console.log("⚠️  Poseidon address not set. Deploy it first, then set POSEIDON_ADDRESS env var.");
    console.log("   Running deploy helper for Poseidon...");
    // Auto-deploy Poseidon using circomlibjs-generated bytecode
    const poseidonContract = await deployPoseidon(deployer);
    const autoAddr = await poseidonContract.getAddress();
    console.log("✅ Poseidon T3 auto-deployed at:", autoAddr);

    await deployVoting(verifierAddr, autoAddr, deployer);
  } else {
    await deployVoting(verifierAddr, poseidonAddr, deployer);
  }
}

async function deployPoseidon(deployer) {
  // Minimal Poseidon T3 deployment using precompiled bytecode from circomlibjs
  // In practice, use: const poseidonContract = await buildPoseidon.deploy();
  // This is a stub — the actual bytecode comes from the circomlibjs library
  console.log("   ℹ️  To deploy Poseidon, run: node scripts/deployPoseidon.js");
  console.log("   Returning placeholder for now...");

  // For a real deployment, install @zk-kit/poseidon and use its deploy helper
  // This placeholder allows the script structure to be complete
  const PoseidonStub = await hre.ethers.getContractFactory("contracts/PoseidonT3Stub.sol:PoseidonT3Stub");
  const poseidon = await PoseidonStub.deploy();
  await poseidon.waitForDeployment();
  return poseidon;
}

async function deployVoting(verifierAddr, poseidonAddr, deployer) {
  // ── 3. Deploy ZKTimeDecayVoting ──
  // Voting period: starts in 5 minutes, lasts 1 hour
  const now = Math.floor(Date.now() / 1000);
  const votingStart = now + 5 * 60;      // 5 minutes from now
  const votingEnd = votingStart + 3600;   // 1 hour duration
  const numChoices = 3;                    // 3 candidates/options

  console.log("\n📦 Deploying ZKTimeDecayVoting...");
  console.log(`   Voting start: ${new Date(votingStart * 1000).toISOString()}`);
  console.log(`   Voting end:   ${new Date(votingEnd * 1000).toISOString()}`);
  console.log(`   Choices: ${numChoices}`);

  const Voting = await hre.ethers.getContractFactory("ZKTimeDecayVoting");
  const voting = await Voting.deploy(
    verifierAddr,
    poseidonAddr,
    votingStart,
    votingEnd,
    numChoices
  );
  await voting.waitForDeployment();
  const votingAddr = await voting.getAddress();
  console.log("✅ ZKTimeDecayVoting deployed at:", votingAddr);

  // ── Summary ──
  console.log("\n════════════════════════════════════════");
  console.log("   DEPLOYMENT SUMMARY");
  console.log("════════════════════════════════════════");
  console.log(`Groth16Verifier:    ${verifierAddr}`);
  console.log(`Poseidon T3:        ${poseidonAddr}`);
  console.log(`ZKTimeDecayVoting:  ${votingAddr}`);
  console.log(`Admin:              ${deployer.address}`);
  console.log(`Voting Start:       ${new Date(votingStart * 1000).toISOString()}`);
  console.log(`Voting End:         ${new Date(votingEnd * 1000).toISOString()}`);
  console.log(`Num Choices:        ${numChoices}`);
  console.log("════════════════════════════════════════\n");

  return { verifierAddr, poseidonAddr, votingAddr };
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ Deployment failed:", error);
    process.exit(1);
  });
